In [ ]:
import torch
from torch import nn
import random
import numpy as np
from tqdm import tqdm
from matplotlib import pyplot as plt

In [ ]:



class Triplet(nn.Module):

    def __init__(self) -> None:
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(10, 512),
            nn.ReLU(inplace=True),
            nn.Linear(512, 512),
            nn.ReLU(inplace=True),
            nn.Linear(512, 1)
        )

        self.loss = nn.CrossEntropyLoss()
        self.optimizer = torch.optim.Adam(self.model.parameters(), lr=0.5)

    def forward(self, inputs):
        y = self.model(inputs)
        return y

    def train(self, inputs, labels):
        outputs = self.forward(inputs)
        loss = self.loss(outputs, labels)

        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()
        return loss


class TripletDataSet(torch.utils.data.Dataset):

    def __init__(self) -> None:
        super().__init__()
        self.counter = 0
        self.items = []

    def __len__(self):
        return 10000

    def __getitem__(self, index):
        if index > len(self):
            raise StopIteration

        if not self.items:
            self.generate()
            idx = index % len(self.items)
        else:
            idx = index % len(self.items)
            if not idx:
                self.generate()

        result = self.items[idx]
        self.counter += 1
        return result

    def evaluate(self, item, turn):
        results = []

        for line in item:
            results.append(sum(line))

        results.append(item.trace())

        T = item.transpose()

        for line in T:
            results.append(sum(line))
        results.append(T.trace())

        if turn > 0:
            return max(results)
        else:
            return min(results)

    def move(self, item, turn):
        args = np.argwhere(item == 0)
        pos = random.choice(args)
        item[(pos[0], pos[1])] = turn

    def generate(self):
        item = np.zeros((3, 3), dtype=np.int8)
        turn = 1

        result = 0

        for _ in range(9):
            self.move(item, turn)
            result = self.evaluate(item, turn)
            res = np.hstack((item.flatten(), np.array([turn])))
            turn *= -1
            self.items.append([res, result])
            if abs(result) == 3:
                break
            item = item.copy()

        for item in self.items:
            item[1] = result

    def draw(self, item):
        # plt.imshow(item)
        for line in item:
            for var in line:
                if var == -1:
                    print("🔵", end="")
                elif var == 1:
                    print("🔴", end="")
                else:
                    print("⬜", end="")
            print()


model = Triplet()
dataset = TripletDataSet()
with tqdm(dataset) as bar:
    for inputs, label in bar:
        loss = model.train(torch.from_numpy(inputs).float(), torch.FloatTensor([label,]))
        bar.set_postfix(loss=loss.item())

In [101]:
def evaluate(item, turn):
    res = np.hstack((item.flatten(), np.array([turn])))
    return float(model.forward(torch.from_numpy(res).float())[0])

In [100]:
item = np.zeros((3, 3), dtype=np.int8)
turn = 1

dataset.move(item, turn)
dataset.draw(item)
print(evaluate(item, turn))

turn *= -1
dataset.move(item, turn)
dataset.draw(item)
print(evaluate(item, turn))

turn *= -1
dataset.move(item, turn)
dataset.draw(item)
print(evaluate(item, turn))

turn *= -1
dataset.move(item, turn)
dataset.draw(item)
print(evaluate(item, turn))

turn *= -1
dataset.move(item, turn)
dataset.draw(item)
print(evaluate(item, turn))

🔴⬜⬜
⬜⬜⬜
⬜⬜⬜
tensor([0.0860], grad_fn=<AddBackward0>)
🔴⬜⬜
⬜⬜🔵
⬜⬜⬜
tensor([0.0919], grad_fn=<AddBackward0>)
🔴⬜⬜
⬜⬜🔵
⬜🔴⬜
tensor([0.1070], grad_fn=<AddBackward0>)
🔴⬜⬜
⬜⬜🔵
🔵🔴⬜
tensor([0.1148], grad_fn=<AddBackward0>)
🔴⬜🔴
⬜⬜🔵
🔵🔴⬜
tensor(0.0994, grad_fn=<SelectBackward0>)
